"""reajustando boleano na bebida

Revision ID: 0f3b820dddef
Revises: 39c29af2aa36
Create Date: 2025-10-07 22:32:25.979981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f3b820dddef'
down_revision: Union[str, Sequence[str], None] = '39c29af2aa36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bebidas', 'desconto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('enderecos', sa.Column('bairro', sa.String(length=100), nullable=False))
    op.alter_column('enderecos', 'cep',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_column('extras', 'tipo')
    op.add_column('pedidos', sa.Column('observacoes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'observacoes')
    op.add_column('extras', sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('enderecos', 'cep',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('enderecos', 'bairro')
    op.alter_column('bebidas', 'desconto',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
