"""Concertando so carrinhos e pedidos

Revision ID: 34e5d5604e07
Revises: 67831f91e0fc
Create Date: 2025-10-11 19:25:39.892566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '34e5d5604e07'
down_revision: Union[str, Sequence[str], None] = '67831f91e0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('itens')
    op.add_column('carrinhos', sa.Column('status', sa.String(length=30), nullable=False))
    op.drop_constraint(op.f('carrinhos_ibfk_1'), 'carrinhos', type_='foreignkey')
    op.drop_column('carrinhos', 'item_id')
    op.add_column('pedidos', sa.Column('carrinho_id', sa.String(length=36), nullable=True))
    op.add_column('pedidos', sa.Column('endereco_entrega', sa.String(length=255), nullable=False))
    op.alter_column('pedidos', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('pedidos_ibfk_2'), 'pedidos', type_='foreignkey')
    op.drop_constraint(op.f('pedidos_ibfk_1'), 'pedidos', type_='foreignkey')
    op.create_foreign_key(None, 'pedidos', 'carrinhos', ['carrinho_id'], ['id'])
    op.drop_column('pedidos', 'retirada_hora')
    op.drop_column('pedidos', 'frete')
    op.drop_column('pedidos', 'observacoes')
    op.drop_column('pedidos', 'retirada_loja')
    op.drop_column('pedidos', 'endereco_id')
    op.drop_column('pedidos', 'item_id')
    op.drop_column('usuarios', 'api_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('api_token', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('pedidos', sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('pedidos', sa.Column('endereco_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('pedidos', sa.Column('retirada_loja', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pedidos', sa.Column('observacoes', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('pedidos', sa.Column('frete', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('pedidos', sa.Column('retirada_hora', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.create_foreign_key(op.f('pedidos_ibfk_1'), 'pedidos', 'enderecos', ['endereco_id'], ['id'])
    op.create_foreign_key(op.f('pedidos_ibfk_2'), 'pedidos', 'itens', ['item_id'], ['id'])
    op.alter_column('pedidos', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('pedidos', 'endereco_entrega')
    op.drop_column('pedidos', 'carrinho_id')
    op.add_column('carrinhos', sa.Column('item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carrinhos_ibfk_1'), 'carrinhos', 'itens', ['item_id'], ['id'])
    op.drop_column('carrinhos', 'status')
    op.create_table('itens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('prato_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('bebida_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('extra_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('criado_em', mysql.DATETIME(), nullable=True),
    sa.Column('atualizado_em', mysql.DATETIME(), nullable=True),
    sa.Column('quantidade_prato', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('quantidade_extra', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bebida_id'], ['bebidas.id'], name=op.f('itens_ibfk_1')),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], name=op.f('itens_ibfk_2')),
    sa.ForeignKeyConstraint(['prato_id'], ['pratos.id'], name=op.f('itens_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('pedido_itens')
    # ### end Alembic commands ###
