"""Alterando os int por numeric

Revision ID: 37d7c9971142
Revises: 12e91d849bb0
Create Date: 2025-10-11 01:00:44.987265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37d7c9971142'
down_revision: Union[str, Sequence[str], None] = '12e91d849bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bebidas', 'preco',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('bebidas', 'precoDesconto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('bebidas', 'unidadeMedida',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=1),
               existing_nullable=False)
    op.alter_column('extras', 'preco',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('extras', 'kcal',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=1),
               existing_nullable=True)
    op.alter_column('extras', 'peso',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=1),
               existing_nullable=False)
    op.alter_column('pedidos', 'frete',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('pedidos', 'total',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pratos', 'preco',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('pratos', 'precoDesconto',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('pratos', 'kcal',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=1),
               existing_nullable=True)
    op.alter_column('pratos', 'peso',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=1),
               existing_nullable=False)
    op.alter_column('usuarios', 'cpf',
               existing_type=mysql.VARCHAR(length=14),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'cpf',
               existing_type=sa.String(length=11),
               type_=mysql.VARCHAR(length=14),
               existing_nullable=False)
    op.alter_column('pratos', 'peso',
               existing_type=sa.Numeric(precision=10, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('pratos', 'kcal',
               existing_type=sa.Numeric(precision=10, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('pratos', 'precoDesconto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('pratos', 'preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('pedidos', 'frete',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('extras', 'peso',
               existing_type=sa.Numeric(precision=10, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('extras', 'kcal',
               existing_type=sa.Numeric(precision=10, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('extras', 'preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('bebidas', 'unidadeMedida',
               existing_type=sa.Numeric(precision=10, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    op.alter_column('bebidas', 'precoDesconto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('bebidas', 'preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
    # ### end Alembic commands ###
