"""adcionando quantidade extra

Revision ID: 39c29af2aa36
Revises: 6359c43f5613
Create Date: 2025-10-07 16:13:49.890140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39c29af2aa36'
down_revision: Union[str, Sequence[str], None] = '6359c43f5613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens', sa.Column('quantidade_prato', sa.Integer(), nullable=False))
    op.add_column('itens', sa.Column('quantidade_extra', sa.Integer(), nullable=False))
    op.drop_column('itens', 'quantidade')
    op.add_column('usuarios', sa.Column('api_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'api_token')
    op.add_column('itens', sa.Column('quantidade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('itens', 'quantidade_extra')
    op.drop_column('itens', 'quantidade_prato')
    # ### end Alembic commands ###
