"""Adcionando endereco no pedido

Revision ID: 4df62931342d
Revises: e556fc3d92f6
Create Date: 2025-10-11 22:40:00.555333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4df62931342d'
down_revision: Union[str, Sequence[str], None] = 'e556fc3d92f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('frete', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pedidos', sa.Column('retirada_boll', sa.Boolean(), nullable=True))
    op.add_column('pedidos', sa.Column('horario_retirada', sa.String(length=50), nullable=True))
    op.add_column('pedidos', sa.Column('observacao', sa.String(length=255), nullable=True))
    op.add_column('pedidos', sa.Column('id_endereco', sa.String(length=36), nullable=True))
    op.alter_column('pedidos', 'carrinho_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('pedidos', 'status',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_foreign_key(None, 'pedidos', 'enderecos', ['id_endereco'], ['id'])
    op.drop_column('pedidos', 'endereco_entrega')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('endereco_entrega', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.alter_column('pedidos', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('pedidos', 'carrinho_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_column('pedidos', 'id_endereco')
    op.drop_column('pedidos', 'observacao')
    op.drop_column('pedidos', 'horario_retirada')
    op.drop_column('pedidos', 'retirada_boll')
    op.drop_column('pedidos', 'frete')
    # ### end Alembic commands ###
