"""criando tabelas e relacionamentos de Bebidas, Extras, Pratos, Tipos, Pedidos, Carrinho, Itens...

Revision ID: 6359c43f5613
Revises: 69559d1137e2
Create Date: 2025-10-06 22:58:19.600506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6359c43f5613'
down_revision: Union[str, Sequence[str], None] = '69559d1137e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_tipo_bebida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('enum_tipo_prato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('extras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bebidas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('precoDesconto', sa.Integer(), nullable=True),
    sa.Column('desconto', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=False),
    sa.Column('unidadeMedida', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_bebida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_bebida_id'], ['enum_tipo_bebida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pratos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('precoDesconto', sa.Integer(), nullable=True),
    sa.Column('desconto', sa.Integer(), nullable=True),
    sa.Column('pessoas', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_prato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_prato_id'], ['enum_tipo_prato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prato_id', sa.String(length=36), nullable=True),
    sa.Column('bebida_id', sa.String(length=36), nullable=True),
    sa.Column('extra_id', sa.String(length=36), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bebida_id'], ['bebidas.id'], ),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ),
    sa.ForeignKeyConstraint(['prato_id'], ['pratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinhos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=False),
    sa.Column('frete', sa.Integer(), nullable=True),
    sa.Column('retirada_loja', sa.Integer(), nullable=True),
    sa.Column('retirada_hora', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enderecos', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.add_column('enderecos', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('atualizado_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'atualizado_em')
    op.drop_column('usuarios', 'criado_em')
    op.drop_column('enderecos', 'atualizado_em')
    op.drop_column('enderecos', 'criado_em')
    op.drop_table('pedidos')
    op.drop_table('carrinhos')
    op.drop_table('itens')
    op.drop_table('pratos')
    op.drop_table('bebidas')
    op.drop_table('extras')
    op.drop_table('enum_tipo_prato')
    op.drop_table('enum_tipo_bebida')
    # ### end Alembic commands ###
