"""tirar tipo dos pratos

Revision ID: 67831f91e0fc
Revises: 37d7c9971142
Create Date: 2025-10-11 12:04:32.354638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67831f91e0fc'
down_revision: Union[str, Sequence[str], None] = '37d7c9971142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pratos', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pratos', sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
