"""adicionar usuario_id no endereco

Revision ID: 69559d1137e2
Revises: de8b9ed1c12c
Create Date: 2025-10-06 16:09:26.826916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69559d1137e2'
down_revision: Union[str, Sequence[str], None] = 'de8b9ed1c12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_confirmado', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('relembrar_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.add_column('enderecos', sa.Column('usuario_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'enderecos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enderecos', type_='foreignkey')
    op.drop_column('enderecos', 'usuario_id')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
