"""Concertando carrinhos e pedidos

Revision ID: dd427b86a841
Revises: 34e5d5604e07
Create Date: 2025-10-11 19:33:10.581073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd427b86a841'
down_revision: Union[str, Sequence[str], None] = '34e5d5604e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('relembrar_token', sa.String(length=255), nullable=True),
    sa.Column('api_token', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('enum_tipo_bebida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('enum_tipo_prato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('extras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('kcal', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('email_confirmado', sa.Integer(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('relembrar_token', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bebidas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precoDesconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Boolean(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=False),
    sa.Column('unidadeMedida', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_bebida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_bebida_id'], ['enum_tipo_bebida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinhos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rua', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('lat', sa.String(length=50), nullable=True),
    sa.Column('lng', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('pratos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precoDesconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('desconto', sa.Integer(), nullable=True),
    sa.Column('pessoas', sa.Integer(), nullable=False),
    sa.Column('kcal', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=1), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('estrela', sa.Integer(), nullable=True),
    sa.Column('legenda', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('tipo_prato_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_prato_id'], ['enum_tipo_prato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrinho_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrinho_id', sa.String(length=36), nullable=False),
    sa.Column('prato_id', sa.String(length=36), nullable=True),
    sa.Column('bebida_id', sa.String(length=36), nullable=True),
    sa.Column('extra_id', sa.String(length=36), nullable=True),
    sa.Column('quantidade_prato', sa.Integer(), nullable=False),
    sa.Column('quantidade_bebida', sa.Integer(), nullable=False),
    sa.Column('quantidade_extra', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bebida_id'], ['bebidas.id'], ),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ),
    sa.ForeignKeyConstraint(['extra_id'], ['extras.id'], ),
    sa.ForeignKeyConstraint(['prato_id'], ['pratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('carrinho_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('endereco_entrega', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_itens')
    op.drop_table('pedidos')
    op.drop_table('carrinho_itens')
    op.drop_table('pratos')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_table('carrinhos')
    op.drop_table('bebidas')
    op.drop_table('usuarios')
    op.drop_table('extras')
    op.drop_table('enum_tipo_prato')
    op.drop_table('enum_tipo_bebida')
    op.drop_table('administradores')
    # ### end Alembic commands ###
