"""Adcionando campo endereco_principal no Endereco

Revision ID: e556fc3d92f6
Revises: dd427b86a841
Create Date: 2025-10-11 21:47:37.616408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e556fc3d92f6'
down_revision: Union[str, Sequence[str], None] = 'dd427b86a841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enderecos', sa.Column('endereco_principal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enderecos', 'endereco_principal')
    # ### end Alembic commands ###
